config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  
  resources :posts, except: [:show] do
    post "/like", to: "likes#like_toggle"
    resources :comments, only: [:create, :destroy]
  end
  
  resources :follows, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :likes
    has_many :liked_users, through: :likes, source: :user
    has_many :comments
    
    mount_uploader :image, PostImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :posts
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments
  
  has_many :follower_relations, foreign_key: "followed_id", class_name: "Follow"
  has_many :followers, through: :follower_relations, source: :follower
  has_many :following_relations, foreign_key: "follower_id", class_name: "Follow"
  has_many :followings, through: :following_relations, source: :followed
  
  mount_uploader :avatar, AvatarUploader
  
  
  def is_like?(post)
    Like.find_by(user_id: self.id, post_id: post.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :check_ownership!, only: [:destroy]
    
    def create
        new_comment = Comment.new(content: params[:content],
                                    post_id: params[:post_id],
                                    user_id: current_user.id)
        new_comment.save
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        @comment.destroy
        redirect_back(fallback_location: root_path)
    end
    
    private
        def check_ownership!
            @comment = Comment.find_by(id: params[:id])
            redirect_back(fallback_location: root_path) if @comment.user.id != current_user.id
        end
        
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
    before_action :authenticate_user!
    
    def create
        Follow.create(followed_id: params[:followed_id],
                        follower_id: current_user.id)
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        Follow.find_by(followed_id: params[:id], follower_id: current_user.id).destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def like_toggle
    like = Like.find_by(user_id: current_user.id,
                        post_id: params[:post_id])

    if like.nil?
      Like.create(user_id: current_user.id,
                  post_id: params[:post_id])
    else
      like.destroy
    end

    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_ownership, only: [:edit, :update, :destroy]
  
  def index
    @posts = Post.all.order('created_at desc')
    @posts_count = current_user.posts.length
  end
  
  def new
  end
  
  def create
    new_post = Post.new(user_id: current_user.id, 
                        content: params[:content],
                        image: params[:image])
    if new_post.save
      redirect_to root_path
    else
      redirect_to new_post_path
    end
  end
  
  def edit
  end
  
  def update

    @post.content = params[:content]
    
    if @post.save
      redirect_to root_path
    else
      render :edit
    end
    
  end
  
  def destroy
    
    @post.destroy
    redirect_to root_path 
  end
  
  private
  
  def check_ownership
     @post = Post.find_by(id: params[:id])
    redirect_to root_path if @post.user_id != current_user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    
    <title>ProjectSns</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <nav>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo">Image SNS</a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="/posts">Posts</a></li>
        <% if user_signed_in? %>
        <li><%= current_user.name %></li>
        <li><%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %></li>
        <% else %>
        <li><a href="/users/sign_in">Sign in</a></li>
        <li><a href="/users/sign_up">Sign up</a></li>
        
        <% end %>
      </ul>
    </div>
  </nav>

  <ul class="sidenav" id="mobile-demo">
        <li><a href="/posts">Posts</a></li>
        <li><a href="#">Sign in</a></li>
        <li><a href="#">Sign up</a></li>
  </ul>
          
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
                <div class="card">
                    <div class="card-content">
                        <span class="card-title"><%= post.user.name %></span>
                        <span><%= post.created_at %></span>
                        <% if user_signed_in? && current_user != post.user %>
                          <% if current_user.followings.include?(post.user) %>
                            <%= form_tag follow_path(post.user.id), method: :delete, class: "right" do %>
                                <button class="btn">팔로우 취소</button>
                            <% end %>
                          <% else %>
                            <%= form_tag follows_path, method: :post, class: "right" do %>
                                <input type="hidden" name="followed_id" value="<%=post.user.id %>">
                                <button class="btn">팔로우</button>
                                
                            <% end %>
                          <% end %>
                        <% end %>
                        <div class="card-image">
                            <% if post.image.url %>
                                <img src="<%= post.image.url %>">
                            <% end %>
                        </div>
                        <p class="pre-line"><%= post.content %></p>
                    </div>

                    <div class="card-action">
                        
                        <%= post.likes.size %> 명이 좋아합니다.
                        <% if current_user.is_like?(post) %>
                            <%= link_to "좋아요 취소", post_like_path(post), method: "post" %>
                        <% else %>
                            <%= link_to "좋아요", post_like_path(post), method: "post" %>
                        <% end %>
                        <% if current_user.id == post.user_id %>
                            <%= link_to "삭제", post_path(post), method: "delete", class: "right" %>
                            <%= link_to "수정", edit_post_path(post), class: "right" %>
                        <% end %>
                        <%= form_tag post_comments_path(post) do %>
                          <div class="input-field">
                            <%= text_area_tag :content, nil, class: "materialize-textarea", placeholder: "댓글을 작성해주세요.", required: true %>
                          </div>
                          <div class="input-field">
                            <%= button_tag "댓글 쓰기", class: "btn" %>
                          </div>
                        <% end %>
                        <% if post.comments.present? %>
                          <ul class="collection">
                          <% post.comments.each do |comment| %>
                            <li class="collection-item">
                              <span class="title"><%= comment.user.name %></span>
                              <span class="right"><%= comment.created_at %></span>
                              <p class="pre-line"><%= comment.content %></p>
                              <% if comment.user.id == current_user.id %>
                                <div><%= link_to "삭제", post_comment_path(post, comment), method: "delete" %></div>
                              <% end %>
                            </li>
                          <% end %>
                          </ul>
                        <% end %>
                    </div>
                </div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="card col s12">
      <div class="card-content">
        <div class="card-title">수정하기</div>
        <%= form_tag post_path(@post), method: "patch" do %>
          <input type="hidden" name="id" value ="<%=@post.id %>">
          <div class="input-field">
            <%= text_area_tag :content, @post.content, class: "materialize-textarea", placeholder: "무슨 생각을 하고 있나요?" %>
          </div>

          <div class="input-field">
            <%= button_tag "수정하기", class: "btn" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
    <div class="row">
        <div class="col s12 m4">
            <div class="card">
                <div class="card-image">
                    <img src="http://materializecss.com/images/office.jpg" />
                </div>
                <div class="card-content">
                    <div class="card-title"><%= current_user.name %></div>
                    <p>이메일 : <%= current_user.email %></p>
                    <p>올린 글 개수 : <%= @posts_count %></p>
                    <p>팔로워: <%= current_user.followers.length %></p>
                    <p>팔로잉: <%= current_user.followings.length %></p>

                    <%= link_to new_post_path do %>
                        <button class="btn">글 쓰기</button>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="col s12 m8">
            <% @posts.each do |post| %>
                <%= render partial: "post", object: post %>
            <% end %>
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="card col s12">
      <div class="card-content">
        <div class="card-title">새 글 작성하기</div>
        <%= form_tag posts_path, multipart: true do %>
        
        <div class-"input-field">
          <%= file_field_tag :image %>
        </div>
          <div class="input-field">
            <%= text_area_tag :content, nil, class: "materialize-textarea", placeholder: "무슨 생각을 하고 있나요?" %>
          </div>

          <div class="input-field">
            <%= button_tag "작성하기", class: "btn" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>